### ISSUE TITLE
Removing the Scrumpy namespace

### ISSUE THREAD

**Issue by hanspagel** [ueberdosis/html-to-prosemirror#11]
As the packaged moved to a new organization I think it would be great to get rid of the Scrumpy namespace to make the usage cleaner.

This will probably be a breaking change. Maybe we can make a “proxy” class to make the transition easy.

Old:
```php
(new \Scrumpy\HtmlToProseMirror\Renderer)->render('<p>Example Text</p>')
```

New:
```php
(new \HtmlToProseMirror\Renderer)->render('<p>Example Text</p>')
```

**Comment by localheinz** [comment]
@hanspagel 

What do you think about using `Ueberdosis` as vendor namespace?

**Comment by hanspagel** [comment]
Would prefer to have it cleaner! No need to “promote” us in that way.
