### ISSUE TITLE
Remove unrecognized tags

### ISSUE THREAD

**Issue by Avatar4eg** [ueberdosis/html-to-prosemirror#8]
If html contains unrecognized tags, like `<span>` - contents will be removed.
For now i had to `strip_tags` with list of `$marks` and `$nodes` supported tags in second parameter:
```
$html= strip_tags(
    $html,
    [
        'strong',
        'b',
        'code',
        'em',
        'i',
        'a',
        'sub',
        'sup',
        'ul',
        'pre',
        'br',
        'h1',
        'h2',
        'h3',
        'h4',
        'h5',
        'h6',
        'img',
        'li',
        'ol',
        'p',
        'tbody',
        'table',
        'td',
        'th',
        'tr',
        'text',
        '#text',
        'user-mention',
    ]
);
```
Maybe this must be first step of `render` function.

**Comment by hanspagel** [comment]
Thanks for reporting! Filtering is a good solution, if you know what tags are supported. 

I extended the Renderer to keep looping through unknown tags (but ignoring them for the output).
